!Config
coordinates: !Coordinates
  item: !Point
    x: 323
    y: 456
  map_top_left: !Point
    x: 1275
    y: 588
  map_bottom_right: !Point
    x: 1323
    y: 638
  alt: !Point
    x: 106
    y: 273
  aug: !Point
    x: 221
    y: 334
  alch: !Point
    x: 488
    y: 279
  scour: !Point
    x: 433
    y: 516
  chaos: !Point
    x: 551
    y: 272
app_settings: !AppSettings
  pyautogui_pause: 0.05000000074505806
  enable_pyautogui_failsafe: null
  enable_performance_logging: false
last_state: !LastState
  crafting_target: Gear
  map_craft_amount: 4
  is_t17: false
  regex_string: ''
  max_currency_use: 500
  is_pre: false
  is_suff: false
